// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: detection/detection.proto

package detection

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Detection_Severity int32

const (
	Detection_NONE   Detection_Severity = 0
	Detection_LOW    Detection_Severity = 1
	Detection_MEDIUM Detection_Severity = 2
	Detection_HIGH   Detection_Severity = 3
)

// Enum value maps for Detection_Severity.
var (
	Detection_Severity_name = map[int32]string{
		0: "NONE",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
	}
	Detection_Severity_value = map[string]int32{
		"NONE":   0,
		"LOW":    1,
		"MEDIUM": 2,
		"HIGH":   3,
	}
)

func (x Detection_Severity) Enum() *Detection_Severity {
	p := new(Detection_Severity)
	*p = x
	return p
}

func (x Detection_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Detection_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_detection_detection_proto_enumTypes[0].Descriptor()
}

func (Detection_Severity) Type() protoreflect.EnumType {
	return &file_detection_detection_proto_enumTypes[0]
}

func (x Detection_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Detection_Severity.Descriptor instead.
func (Detection_Severity) EnumDescriptor() ([]byte, []int) {
	return file_detection_detection_proto_rawDescGZIP(), []int{3, 0}
}

type DetectionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dets []*Detection `protobuf:"bytes,1,rep,name=dets,proto3" json:"dets,omitempty"`
}

func (x *DetectionData) Reset() {
	*x = DetectionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detection_detection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetectionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionData) ProtoMessage() {}

func (x *DetectionData) ProtoReflect() protoreflect.Message {
	mi := &file_detection_detection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionData.ProtoReflect.Descriptor instead.
func (*DetectionData) Descriptor() ([]byte, []int) {
	return file_detection_detection_proto_rawDescGZIP(), []int{0}
}

func (x *DetectionData) GetDets() []*Detection {
	if x != nil {
		return x.Dets
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detection_detection_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_detection_detection_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_detection_detection_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type Threat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThreatListName string   `protobuf:"bytes,1,opt,name=threat_list_name,json=threatListName,proto3" json:"threat_list_name,omitempty"`
	ThreatNames    []string `protobuf:"bytes,2,rep,name=threat_names,json=threatNames,proto3" json:"threat_names,omitempty"`
}

func (x *Threat) Reset() {
	*x = Threat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detection_detection_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Threat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Threat) ProtoMessage() {}

func (x *Threat) ProtoReflect() protoreflect.Message {
	mi := &file_detection_detection_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Threat.ProtoReflect.Descriptor instead.
func (*Threat) Descriptor() ([]byte, []int) {
	return file_detection_detection_proto_rawDescGZIP(), []int{2}
}

func (x *Threat) GetThreatListName() string {
	if x != nil {
		return x.ThreatListName
	}
	return ""
}

func (x *Threat) GetThreatNames() []string {
	if x != nil {
		return x.ThreatNames
	}
	return nil
}

type Detection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string             `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Title       string             `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Sev         Detection_Severity `protobuf:"varint,3,opt,name=sev,proto3,enum=detection.Detection_Severity" json:"sev,omitempty"`
	ActionType  string             `protobuf:"bytes,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	ServiceName string             `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ScoutName   string             `protobuf:"bytes,6,opt,name=scout_name,json=scoutName,proto3" json:"scout_name,omitempty"`
	Node        *Node              `protobuf:"bytes,7,opt,name=node,proto3" json:"node,omitempty"`
	Threats     []*Threat          `protobuf:"bytes,8,rep,name=threats,proto3" json:"threats,omitempty"`
}

func (x *Detection) Reset() {
	*x = Detection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detection_detection_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_detection_detection_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_detection_detection_proto_rawDescGZIP(), []int{3}
}

func (x *Detection) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Detection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Detection) GetSev() Detection_Severity {
	if x != nil {
		return x.Sev
	}
	return Detection_NONE
}

func (x *Detection) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *Detection) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Detection) GetScoutName() string {
	if x != nil {
		return x.ScoutName
	}
	return ""
}

func (x *Detection) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Detection) GetThreats() []*Threat {
	if x != nil {
		return x.Threats
	}
	return nil
}

type ProcessedReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rc bool `protobuf:"varint,1,opt,name=rc,proto3" json:"rc,omitempty"`
}

func (x *ProcessedReply) Reset() {
	*x = ProcessedReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detection_detection_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedReply) ProtoMessage() {}

func (x *ProcessedReply) ProtoReflect() protoreflect.Message {
	mi := &file_detection_detection_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedReply.ProtoReflect.Descriptor instead.
func (*ProcessedReply) Descriptor() ([]byte, []int) {
	return file_detection_detection_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessedReply) GetRc() bool {
	if x != nil {
		return x.Rc
	}
	return false
}

var File_detection_detection_proto protoreflect.FileDescriptor

var file_detection_detection_proto_rawDesc = []byte{
	0x0a, 0x19, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x64, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x39, 0x0a, 0x0d, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x65, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x64, 0x65, 0x74,
	0x73, 0x22, 0x1a, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22, 0x55, 0x0a,
	0x06, 0x54, 0x68, 0x72, 0x65, 0x61, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x68, 0x72, 0x65, 0x61,
	0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x74, 0x68, 0x72, 0x65, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x68, 0x72, 0x65, 0x61, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x68, 0x72, 0x65, 0x61, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x22, 0xd0, 0x02, 0x0a, 0x09, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x2f, 0x0a, 0x03,
	0x73, 0x65, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x64, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x52, 0x03, 0x73, 0x65, 0x76, 0x12, 0x1f, 0x0a,
	0x0b, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x23, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x74, 0x68, 0x72, 0x65, 0x61, 0x74, 0x73,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x54, 0x68, 0x72, 0x65, 0x61, 0x74, 0x52, 0x07, 0x74, 0x68, 0x72, 0x65, 0x61,
	0x74, 0x73, 0x22, 0x33, 0x0a, 0x08, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x08,
	0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x4f, 0x57, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45, 0x44, 0x49, 0x55, 0x4d, 0x10, 0x02, 0x12, 0x08, 0x0a,
	0x04, 0x48, 0x49, 0x47, 0x48, 0x10, 0x03, 0x22, 0x20, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x72, 0x63, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x73, 0x6f, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_detection_detection_proto_rawDescOnce sync.Once
	file_detection_detection_proto_rawDescData = file_detection_detection_proto_rawDesc
)

func file_detection_detection_proto_rawDescGZIP() []byte {
	file_detection_detection_proto_rawDescOnce.Do(func() {
		file_detection_detection_proto_rawDescData = protoimpl.X.CompressGZIP(file_detection_detection_proto_rawDescData)
	})
	return file_detection_detection_proto_rawDescData
}

var file_detection_detection_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_detection_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_detection_detection_proto_goTypes = []interface{}{
	(Detection_Severity)(0), // 0: detection.Detection.Severity
	(*DetectionData)(nil),   // 1: detection.DetectionData
	(*Node)(nil),            // 2: detection.Node
	(*Threat)(nil),          // 3: detection.Threat
	(*Detection)(nil),       // 4: detection.Detection
	(*ProcessedReply)(nil),  // 5: detection.ProcessedReply
}
var file_detection_detection_proto_depIdxs = []int32{
	4, // 0: detection.DetectionData.dets:type_name -> detection.Detection
	0, // 1: detection.Detection.sev:type_name -> detection.Detection.Severity
	2, // 2: detection.Detection.node:type_name -> detection.Node
	3, // 3: detection.Detection.threats:type_name -> detection.Threat
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_detection_detection_proto_init() }
func file_detection_detection_proto_init() {
	if File_detection_detection_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_detection_detection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetectionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detection_detection_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detection_detection_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Threat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detection_detection_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Detection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detection_detection_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessedReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_detection_detection_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_detection_detection_proto_goTypes,
		DependencyIndexes: file_detection_detection_proto_depIdxs,
		EnumInfos:         file_detection_detection_proto_enumTypes,
		MessageInfos:      file_detection_detection_proto_msgTypes,
	}.Build()
	File_detection_detection_proto = out.File
	file_detection_detection_proto_rawDesc = nil
	file_detection_detection_proto_goTypes = nil
	file_detection_detection_proto_depIdxs = nil
}
